#!/bin/zsh

# Generate dotfiles_config
DOTFILES=$(pwd)
echo "###############################################" > ~/.dotfiles_config
echo "# This file is generated by hawkins/dotfiles. #" >> ~/.dotfiles_config
echo "# Run dotfiles/install.sh to repair this.     #" >> ~/.dotfiles_config
echo "###############################################" >> ~/.dotfiles_config
echo "export DOTFILES=$DOTFILES" >> ~/.dotfiles_config

# Handle submodules before we do anything else
git submodule update --init --recursive

# Link special purpose files
ln -fn $DOTFILES/zsh/zeit.zsh-theme ~/.oh-my-zsh/themes/zeit.zsh-theme && echo "Installed ZSH Theme: Zeit"

# Actually link the rest of the files
stow .

# Finally, prepare the shell with new dotfiles
source ~/.zshrc
