#!/bin/zsh

# Generate dotfiles_config
DOTFILES=$(pwd)
echo "###############################################" > ~/.dotfiles_config
echo "# This file is generated by hawkins/dotfiles. #" >> ~/.dotfiles_config
echo "# Run dotfiles/install.sh to repair this.     #" >> ~/.dotfiles_config
echo "###############################################" >> ~/.dotfiles_config
echo "export DOTFILES=$DOTFILES" >> ~/.dotfiles_config


# Seriously, never submodules
git clone git@github.com:hawkins/kickstart.nvim.git $DOTFILES/.config/nvim
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
curl https://raw.githubusercontent.com/zakaziko99/agnosterzak-ohmyzsh-theme/master/agnosterzak.zsh-theme > ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/themes/agnosterzak.zsh-theme


# Link special purpose files
ln -fn $DOTFILES/zsh/zeit.zsh-theme ~/.oh-my-zsh/themes/zeit.zsh-theme && echo "Installed ZSH Theme: Zeit"

# Actually link the rest of the files
stow .
# If this errors, you may want to actually bring in the existing files your box already has with:
# stow . --adopt

# Finally, prepare the shell with new dotfiles
source ~/.zshrc
