-- DO NOT EDIT THIS FILE. MAKE YOUR CHANGES IN CUSTOM.D.

hl.on("hyprland.start", function()
    if not os.getenv("HLDE_NO_WALKER") then
        hl.exec_cmd("elephant")
        hl.exec_cmd("GSK_RENDERER=cairo walker -t hypr --gapplication-service")
    end

    if not os.getenv("HLDE_NO_HYPRIDLE") then
        hl.exec_cmd("hypridle")
    end

    hl.exec_cmd("QS_NO_RELOAD_POPUP=1 QML_DISABLE_DISK_CACHE=1 quickshell")
end)
