-- DO NOT EDIT THIS FILE. MAKE YOUR CHANGES IN CUSTOM.D.

hl.env("XCURSOR_SIZE",              "24")
hl.env("HYPRCURSOR_SIZE",           "24")
hl.env("XCURSOR_THEME",             "XCursor-Pro-Dark")
hl.env("HYPRCURSOR_THEME",          "XCursor-Pro-Dark-Hyprcursor")
