-- DO NOT EDIT THIS FILE. MAKE YOUR CHANGES IN CUSTOM.D.

hl.window_rule({ match = { class = ".*" }, suppress_event = "maximize" })

hl.window_rule({
    match = { class = "^$", title = "^$", xwayland = true, float = true, fullscreen = false, pin = false },
    no_focus = true,
})

hl.layer_rule({
    match        = { namespace = "walker" },
    blur         = true,
    ignore_alpha = 0.41,
})

hl.layer_rule({
    match        = { namespace = "hyprland-shell:bar" },
    blur         = true,
    blur_popups  = true,
    ignore_alpha = 0.41,
})

hl.layer_rule({
    match        = { namespace = "hyprland-shell:notifs" },
    blur         = true,
    ignore_alpha = 0.41,
    no_anim      = true,
})

hl.window_rule({ match = { class = "hyprland-share-picker" }, float = true })
