
$background = rgba(151218ff)

$error = rgba(ffb4abff)

$error_container = rgba(93000aff)

$inverse_on_surface = rgba(322f35ff)

$inverse_primary = rgba(6b538cff)

$inverse_surface = rgba(e7e0e8ff)

$on_background = rgba(e7e0e8ff)

$on_error = rgba(690005ff)

$on_error_container = rgba(ffdad6ff)

$on_primary = rgba(3b255bff)

$on_primary_container = rgba(eddcffff)

$on_primary_fixed = rgba(250e44ff)

$on_primary_fixed_variant = rgba(523c73ff)

$on_secondary = rgba(352d40ff)

$on_secondary_container = rgba(ebddf7ff)

$on_secondary_fixed = rgba(20182aff)

$on_secondary_fixed_variant = rgba(4c4357ff)

$on_surface = rgba(e7e0e8ff)

$on_surface_variant = rgba(cbc4cfff)

$on_tertiary = rgba(4b252eff)

$on_tertiary_container = rgba(ffd9dfff)

$on_tertiary_fixed = rgba(321019ff)

$on_tertiary_fixed_variant = rgba(653b44ff)

$outline = rgba(958e99ff)

$outline_variant = rgba(4a454eff)

$primary = rgba(d6bbfbff)

$primary_container = rgba(523c73ff)

$primary_fixed = rgba(eddcffff)

$primary_fixed_dim = rgba(d6bbfbff)

$scrim = rgba(000000ff)

$secondary = rgba(cec2daff)

$secondary_container = rgba(4c4357ff)

$secondary_fixed = rgba(ebddf7ff)

$secondary_fixed_dim = rgba(cec2daff)

$shadow = rgba(000000ff)

$source_color = rgba(8b56d7ff)

$surface = rgba(151218ff)

$surface_bright = rgba(3b383eff)

$surface_container = rgba(211e24ff)

$surface_container_high = rgba(2c292fff)

$surface_container_highest = rgba(37333aff)

$surface_container_low = rgba(1d1a20ff)

$surface_container_lowest = rgba(100d12ff)

$surface_dim = rgba(151218ff)

$surface_tint = rgba(d6bbfbff)

$surface_variant = rgba(4a454eff)

$tertiary = rgba(f2b7c2ff)

$tertiary_container = rgba(653b44ff)

$tertiary_fixed = rgba(ffd9dfff)

$tertiary_fixed_dim = rgba(f2b7c2ff)



$background_raw = 151218

$error_raw = ffb4ab

$error_container_raw = 93000a

$inverse_on_surface_raw = 322f35

$inverse_primary_raw = 6b538c

$inverse_surface_raw = e7e0e8

$on_background_raw = e7e0e8

$on_error_raw = 690005

$on_error_container_raw = ffdad6

$on_primary_raw = 3b255b

$on_primary_container_raw = eddcff

$on_primary_fixed_raw = 250e44

$on_primary_fixed_variant_raw = 523c73

$on_secondary_raw = 352d40

$on_secondary_container_raw = ebddf7

$on_secondary_fixed_raw = 20182a

$on_secondary_fixed_variant_raw = 4c4357

$on_surface_raw = e7e0e8

$on_surface_variant_raw = cbc4cf

$on_tertiary_raw = 4b252e

$on_tertiary_container_raw = ffd9df

$on_tertiary_fixed_raw = 321019

$on_tertiary_fixed_variant_raw = 653b44

$outline_raw = 958e99

$outline_variant_raw = 4a454e

$primary_raw = d6bbfb

$primary_container_raw = 523c73

$primary_fixed_raw = eddcff

$primary_fixed_dim_raw = d6bbfb

$scrim_raw = 000000

$secondary_raw = cec2da

$secondary_container_raw = 4c4357

$secondary_fixed_raw = ebddf7

$secondary_fixed_dim_raw = cec2da

$shadow_raw = 000000

$source_color_raw = 8b56d7

$surface_raw = 151218

$surface_bright_raw = 3b383e

$surface_container_raw = 211e24

$surface_container_high_raw = 2c292f

$surface_container_highest_raw = 37333a

$surface_container_low_raw = 1d1a20

$surface_container_lowest_raw = 100d12

$surface_dim_raw = 151218

$surface_tint_raw = d6bbfb

$surface_variant_raw = 4a454e

$tertiary_raw = f2b7c2

$tertiary_container_raw = 653b44

$tertiary_fixed_raw = ffd9df

$tertiary_fixed_dim_raw = f2b7c2
