source = ~/.config/hypr/hyprlockColors.conf

general {
    grace = 0
    hide_cursor = true
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 6
    brightness = 0.7
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = $on_surface
    font_size = 80
    font_family = Noto Sans Bold
    position = 0, 120
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] echo "$(date +"%A, %B %-d")"
    color = $on_surface_variant
    font_size = 18
    font_family = Noto Sans
    position = 0, 40
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 280, 52
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.2
    outer_color = $primary
    inner_color = $surface_container
    font_color = $on_surface
    fade_on_empty = true
    placeholder_text = <span foreground="##cbc4cf">password</span>
    fail_color = $error
    fail_text = <i>$FAIL ($ATTEMPTS)</i>
    capslock_color = $error
    position = 0, -60
    halign = center
    valign = center
}
