-- DO NOT EDIT THIS FILE. MAKE YOUR CHANGES IN CUSTOM.D.
-- HLDE default keybinds (overridden by custom.d/regular/binds.lua via hl.unbind("all"))

hl.bind("SUPER + Q",       hl.dsp.exec_cmd(terminal))
hl.bind("SUPER + C",       hl.dsp.window.close())
hl.bind("SUPER + M",       hl.dsp.exit())
hl.bind("SUPER + E",       hl.dsp.exec_cmd(fileManager))
hl.bind("SUPER + V",       hl.dsp.window.float({ action = "toggle" }))
hl.bind("SUPER + R",       hl.dsp.exec_cmd(menu))
hl.bind("SUPER + P",       hl.dsp.window.pseudo())
hl.bind("SUPER + J",       hl.dsp.layout("togglesplit"))
hl.bind("SUPER + L",       hl.dsp.exec_cmd(lockscreen))
hl.bind("SUPER + F",       hl.dsp.window.fullscreen())
hl.bind("SUPER + SHIFT + F", hl.dsp.window.fullscreen({ mode = "maximized" }))
hl.bind("Print",           hl.dsp.exec_cmd(screenshot))

hl.bind("SUPER + left",  hl.dsp.focus({ direction = "l" }))
hl.bind("SUPER + right", hl.dsp.focus({ direction = "r" }))
hl.bind("SUPER + up",    hl.dsp.focus({ direction = "u" }))
hl.bind("SUPER + down",  hl.dsp.focus({ direction = "d" }))

for i = 1, 9 do
    hl.bind("SUPER + " .. i,          hl.dsp.focus({ workspace = i }))
    hl.bind("SUPER + SHIFT + " .. i,  hl.dsp.window.move({ workspace = i }))
end
hl.bind("SUPER + 0",         hl.dsp.focus({ workspace = 10 }))
hl.bind("SUPER + SHIFT + 0", hl.dsp.window.move({ workspace = 10 }))

hl.bind("SUPER + S",         hl.dsp.workspace.toggle_special("first"))
hl.bind("SUPER + SHIFT + S", hl.dsp.window.move({ workspace = "special:first" }))

hl.bind("SUPER + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind("SUPER + mouse_up",   hl.dsp.focus({ workspace = "e-1" }))

hl.bind("SUPER + mouse:272", hl.dsp.window.drag(),   { mouse = true })
hl.bind("SUPER + mouse:273", hl.dsp.window.resize(), { mouse = true })

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"),  { repeating = true, locked = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),         { repeating = true, locked = true })
hl.bind("XF86AudioMute",        hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),        { repeating = true, locked = true })
hl.bind("XF86AudioMicMute",     hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),      { repeating = true, locked = true })
hl.bind("XF86MonBrightnessUp",  hl.dsp.exec_cmd("qs msg brightness increment"),                       { repeating = true, locked = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("qs msg brightness decrement"),                      { repeating = true, locked = true })

hl.bind("XF86AudioNext",  hl.dsp.exec_cmd("playerctl next"),        { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"),  { locked = true })
hl.bind("XF86AudioPlay",  hl.dsp.exec_cmd("playerctl play-pause"),  { locked = true })
hl.bind("XF86AudioPrev",  hl.dsp.exec_cmd("playerctl previous"),    { locked = true })
