-- DO NOT EDIT THIS FILE. MAKE YOUR CHANGES IN CUSTOM.D.

if not os.getenv("HLDE_NO_MAXIMIZED") then
    hl.workspace_rule({ workspace = "f[1]", gaps_out = 0, border_size = 0, no_rounding = true })
end
