-- DO NOT EDIT THIS FILE. MAKE YOUR CHANGES IN CUSTOM.D.

terminal    = "kitty"
fileManager = "dolphin"
menu        = "walker -t hypr"
lockscreen  = "hyprlock"
screenshot  = "grimblast --freeze --notify copysave area"
