-- Auto-generated by wallust from current wallpaper colors.

background = "rgb(19151F)"
foreground = "rgb(F1EEF4)"
color0     = "rgb(403C47)"
color1     = "rgb(5A5E76)"
color2     = "rgb(805F69)"
color3     = "rgb(5F7677)"
color4     = "rgb(B156B6)"
color5     = "rgb(727FB2)"
color6     = "rgb(A29BA7)"
color7     = "rgb(E3DFE7)"
color8     = "rgb(9F9CA1)"
color9     = "rgb(787D9E)"
color10    = "rgb(AA7F8C)"
color11    = "rgb(7F9D9F)"
color12    = "rgb(EC73F3)"
color13    = "rgb(98A9ED)"
color14    = "rgb(D8CFDF)"
color15    = "rgb(E3DFE7)"

-- Mapped to Hyprland settings variables
primary_fixed             = "rgb(EC73F3)"
primary_fixed_dim         = "rgb(B156B6)"
surface_container         = "rgb(403C47)"
surface_container_low_raw = "403C47"

-- Override border colors (must run after regular/settings.lua)
hl.config({
    general = {
        col = {
            active_border   = { colors = { "rgb(EC73F3)", "rgb(B156B6)" }, angle = 45 },
            inactive_border = "rgb(403C47)",
        },
    },
})
