# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(2E2A28)
$foreground = rgb(FCFAF9)
$color0 = rgb(544F4D)
$color1 = rgb(563F31)
$color2 = rgb(864013)
$color3 = rgb(795E4F)
$color4 = rgb(747471)
$color5 = rgb(A1877A)
$color6 = rgb(B8B5B2)
$color7 = rgb(F2F0EE)
$color8 = rgb(A9A8A6)
$color9 = rgb(735441)
$color10 = rgb(B35619)
$color11 = rgb(A17D69)
$color12 = rgb(9B9A96)
$color13 = rgb(D6B4A3)
$color14 = rgb(F5F1ED)
$color15 = rgb(F2F0EE)
