#!/bin/bash

if [ -z "$1" ]; then
    echo "No path supplied"
    exit 1
fi

if [ ! -f "$1" ]; then
    echo "File doesn't exist"
    exit 1
fi

echo "$(realpath $1)" > ~/.config/hyprland-de/wallpaper.conf

cat <<EOF > ~/.config/hypr/hyprpaper.conf
# Do not edit this file, your changes will be overwritten
preload=$1
wallpaper=,$1
EOF

nohup wallust run "$1" > /dev/null >&/dev/null &
nohup matugen image "$1" > /dev/null >&/dev/null &

if [ "$HYPRLAND_INSTANCE_SIGNATURE" = "" ]; then
    echo "Done!"
    exit 0
fi

if [ -z "$HLDE_NO_HYPRPAPER" ]; then
    killall hyprpaper > /dev/null || echo ""
    hyprctl dispatch exec hyprpaper || echo ""
fi
killall walker > /dev/null || echo ""
GSK_RENDERER=cairo nohup walker --gapplication-service >&/dev/null &

echo "Done!"
