#!/bin/bash

WALLPAPER_PATH="$*"

if [ -z "$WALLPAPER_PATH" ]; then
    echo "No path supplied"
    exit 1
fi

if [ ! -f "$WALLPAPER_PATH" ]; then
    echo "File doesn't exist: $WALLPAPER_PATH"
    exit 1
fi

echo "realpath"
echo "$(realpath "$WALLPAPER_PATH")" > ~/.config/hyprland-de/wallpaper.conf

echo "cat eof"
cat <<EOF > ~/.config/hypr/hyprpaper.conf
# Do not edit this file, your changes will be overwritten
preload=$WALLPAPER_PATH
wallpaper=,$WALLPAPER_PATH
EOF

echo "wallust"
nohup wallust run "$WALLPAPER_PATH" > /dev/null >&/dev/null &
echo "matugen"
nohup matugen image "$WALLPAPER_PATH" > /dev/null >&/dev/null &

if [ "$HYPRLAND_INSTANCE_SIGNATURE" = "" ]; then
    echo "Done!"
    exit 0
fi

echo "hyprpaper"
if [ -z "$HLDE_NO_HYPRPAPER" ]; then
    killall hyprpaper > /dev/null || echo ""
    hyprctl dispatch exec hyprpaper || echo ""
fi
killall walker > /dev/null || echo ""
GSK_RENDERER=cairo nohup walker --gapplication-service >&/dev/null &

echo "Done!"
